version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  api:
    build: .
    container_name: bookstore-api
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/bookstore
      - JWT_SECRET=sanuyadav
      - JWT_EXPIRES_IN=1d

volumes:
  mongo-data:
